travis:
  secure:
    BINSTAR_TOKEN: QZOw7qisAX6PAdc6w+NaADAcIsOIfup5f1A60KblBq7CHVZAxw3FX7O4APulkYUCDIB/ySemecAXoJr6sbRVeW57FiohPjpHQxyQAMBuBzea8mYTCa3mz3xyyXn6dabrwiCSYjAZHKkV1ZVOkog9ajqF+8mMxCrAIcvKa5rWXfYjv02L3r5Dp7vy53MDVR1MqMVMiOJrUvEe6BlvTpeoutfe8Ue9IINy1DVK6uT6shuwHRcvSenHPUlKArH1eh3KQs6jJOGSqS4HTw9bu358WWakV2pDg+71Qf4JUCY+I9KiopLfLY8EBH3/8b31d96Iwv/C28uj5tUxpb8tBbaaBEtGNarqOSncrT2t90fmaVuyJ4Q+kPdUnFDy3kPT3cMuydATg/MLa1JrybhrGNHipUD/qRbqxO7aNx7Asf3UHjuqHxLCR4/X2zDM1gPMuh3vxg4s2euL9YxeEeEX6L6OcFEv5vPkJVg3wi7429vhOnTZ9kaacbtT+h9mlqLpHE5dLqK+7P/M4roXDe0SiRZeL0vMW5Ogzv3Ma3EEku+7JuuHr7/bDjKRPm/hQIzCz4Dq80ibqVW4KpW+zBLEXRjDDMhVh81hz6oonQ+Xz8erRdBFm38BZswGZqiZW32D6l8CiRevB27bOwOz03Bpx/anETEMeIJVarw6SVmbvcJlC30=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
