travis:
  secure:
    BINSTAR_TOKEN: il3xBnP4N/6Cs+nO+cNcWNnurwGXD5iuJEVpXFvvJL2KkaEsvcGpQJg43+qVRKES6kPyY4Mf2IWvCvxXi5sXGEudhNkOd33FhvAWKesFOYzcTR9F3bqNnE8qPOV0ohEV5ULaZFlZrwdfe6Rte+A685iBznoFhr11yrMNlKw3Rd0UomhYUltyilxhvYuNQGPcaLtUvwO8hrQanuIIZFc6C9KaLk9OyCairHwFuts31GjDTrnwArSBNIcY8L4ONgfjNnDzf5SXXVCXP2wPLZ3qw7BizaiHJtwToN4/yJvI7xkfD5xfxYW0/v63Hxf4455YgYOcWTLbmjhE94o5BZtJWZtK2GCPplkOKMbulQzSPvooFrjh+RscpCUJdDOENw+u3zkbiOkl9qpVzvxkkZPOzROprelm7wsmMIOut6Oum44p5QAf/iEPKy60dMj8YNPjUf5nu11CJ5nA/LvG2SpY+uLUtfPu28o0TaypdzR4O4PBRrE91r23c+a7TqLuX5GwzMD7TKD/ZZ+f0G9CbCg6mIbBjTi4/sWagXWb0+thX8FyWrzrt+aoIPznQduUIAnjhEcrZDlAgFhOVRFG1+Mr3CD6fNwa3X0wfezEEwM2zJmqXDZGquUjE0uDKmXibzgRdG8S/RqLp+2gKo+zzHKsJONF1e7WBRxaLBNlznC5p30=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
